
//----------------------------------------------------
// The following code was generated by CUP v0.11b ${cupversion} (SVN rev )
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 23;
  public static final int DIVIDE = 28;
  public static final int INPUTOP = 20;
  public static final int EQUALS = 32;
  public static final int TUPLE = 5;
  public static final int UMINUS = 44;
  public static final int STRLITERAL = 10;
  public static final int INTEGER = 2;
  public static final int LPAREN = 13;
  public static final int GREATER = 34;
  public static final int LESS = 36;
  public static final int MINUS = 26;
  public static final int WRITE = 42;
  public static final int RPAREN = 14;
  public static final int NOT = 31;
  public static final int AND = 29;
  public static final int OR = 30;
  public static final int COMMA = 18;
  public static final int OUTPUTOP = 21;
  public static final int PLUS = 25;
  public static final int IF = 38;
  public static final int LESSEQ = 37;
  public static final int ASSIGN = 22;
  public static final int DOT = 19;
  public static final int ID = 8;
  public static final int EOF = 0;
  public static final int RETURN = 43;
  public static final int MINUSMINUS = 24;
  public static final int TRUE = 6;
  public static final int error = 1;
  public static final int LCURLY = 11;
  public static final int LSQBRACKET = 15;
  public static final int VOID = 4;
  public static final int RCURLY = 12;
  public static final int INTLITERAL = 9;
  public static final int TIMES = 27;
  public static final int COLON = 17;
  public static final int ELSE = 39;
  public static final int LOGICAL = 3;
  public static final int READ = 41;
  public static final int WHILE = 40;
  public static final int NOTEQUALS = 33;
  public static final int RSQBRACKET = 16;
  public static final int GREATEREQ = 35;
  public static final int FALSE = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "LOGICAL",
  "VOID",
  "TUPLE",
  "TRUE",
  "FALSE",
  "ID",
  "INTLITERAL",
  "STRLITERAL",
  "LCURLY",
  "RCURLY",
  "LPAREN",
  "RPAREN",
  "LSQBRACKET",
  "RSQBRACKET",
  "COLON",
  "COMMA",
  "DOT",
  "INPUTOP",
  "OUTPUTOP",
  "ASSIGN",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "AND",
  "OR",
  "NOT",
  "EQUALS",
  "NOTEQUALS",
  "GREATER",
  "GREATEREQ",
  "LESS",
  "LESSEQ",
  "IF",
  "ELSE",
  "WHILE",
  "READ",
  "WRITE",
  "RETURN",
  "UMINUS"
  };
}

